### PR TITLE
remove loader file uploads

### LINKED ISSUE #27: Loader release upload should be removed
image

### PR DESCRIPTION
**Pull request by made-by-traxam**
Closes #27

### CODE REVIEW

**Comment by made-by-traxam** [comment]
Is this sufficient or do I need to remove it at some point in the frontend too? I tested it and the loader version creation still works but maybe I'm missing something @Felix-Puetz

**Comment by Felix-Puetz** [comment]
The json structure basically defines Whats rendered in the Frontend so this might be sufficient.
But what about the api? And the database ?

**Comment by made-by-traxam** [comment]
I thought I'd work on it as part of #32 but I can see why this would be a better place for that. I'll work on it again

**Review by Felix-Puetz — CHANGES_REQUESTED** [review]
see comment above

**Review by Felix-Puetz — APPROVED** [review]

**Pull request merged**
